apiVersion: v1
kind: Service
metadata:
  name: hello-world
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: hello-world

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: hello-world
spec:
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      containers:
      - image: 724258426085.dkr.ecr.us-east-1.amazonaws.com/k8s/jenkins-test:latest
        name: hello-world
        ports:
        - containerPort: 80
          name: http
