apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: ClusterIP
  ports:
  - port: 80
    name: http
    targetPort: 80
  selector:
    app: nginx

---

apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: nginx
spec:
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - image: 724258426085.dkr.ecr.us-east-1.amazonaws.com/k8s/jenkins-test:${build_tag}
        name: nginx
        ports:
        - containerPort: 80
          name: http
